# Generated by Django 4.0.1 on 2022-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnails',
            field=models.ImageField(upload_to='backup-photos'),
        ),
    ]
